// apps/remote-react/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";
import AwesomeButton from "./components/AwesomeButton";
import Counter from "./components/Counter";

import "./index.css";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div className="text-blue-700">Name: Remote React</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
    <AwesomeButton />
    <Counter />
  </div>
);
ReactDOM.render(<App />, document.getElementById("app"));

// apps/remote-solid/src/App.tsx
import { render } from "solid-js/web";
import Counter from "./components/Counter";
import "./index.css";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: remote-solid</div>
    <div>Framework: solid-js</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
    <Counter />
  </div>
);
render(App, document.getElementById("app"));
